const Data = {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/download.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReview: 10,
    },
    {
      _id: '2',
      name: 'Fit Shirt',
      category: 'shirts',
      image: '/images/download.jpg',
      brand: 'Levis',
      price: 67,
      rating: 4.2,
      numReview: 15,
    },
    {
      _id: '3',
      name: 'Best Pants',
      category: 'pants',
      image: '/images/download.jpg',
      brand: 'Nike',
      price: 50,
      rating: 3.9,
      numReview: 11,
    },
    {
      _id: '4',
      name: 'T-Shirt',
      category: 'shirts',
      image: '/images/download.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.6,
      numReview: 10,
    },
    {
      _id: '5',
      name: 'lower Pant',
      category: 'pants',
      image: '/images/download.jpg',
      brand: 'Miacawer',
      price: 61,
      rating: 4.0,
      numReview: 8,
    },
  ],
};

module.exports = Data;
