export const USER_SIGN_REQUEST = 'USER_SIGN_REQUEST';
export const USER_SIGN_SUCCESS = 'USER_SIGN_SUCCESS';
export const USER_SIGN_FAIL = 'USER_SIGN_FAIL';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
